// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8A49KCO4OwwTggOVfj5uhl0d5bV9_Gk',
    appId: '1:507753071893:web:77eb04bec17b64516b951c',
    messagingSenderId: '507753071893',
    projectId: 'api-project-e4ac1',
    authDomain: 'api-project-e4ac1.firebaseapp.com',
    databaseURL: 'https://api-project-e4ac1-default-rtdb.firebaseio.com',
    storageBucket: 'api-project-e4ac1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Md5yZBHuRmC4LbOKefqbufeS3yFwmvs',
    appId: '1:507753071893:android:44a1d165bf57d1706b951c',
    messagingSenderId: '507753071893',
    projectId: 'api-project-e4ac1',
    databaseURL: 'https://api-project-e4ac1-default-rtdb.firebaseio.com',
    storageBucket: 'api-project-e4ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrbItK3C1tiQICksxI-WBrwBRNTEMWDI',
    appId: '1:507753071893:ios:1dd4a28e28cce40c6b951c',
    messagingSenderId: '507753071893',
    projectId: 'api-project-e4ac1',
    databaseURL: 'https://api-project-e4ac1-default-rtdb.firebaseio.com',
    storageBucket: 'api-project-e4ac1.firebasestorage.app',
    iosBundleId: 'com.example.iteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrbItK3C1tiQICksxI-WBrwBRNTEMWDI',
    appId: '1:507753071893:ios:1dd4a28e28cce40c6b951c',
    messagingSenderId: '507753071893',
    projectId: 'api-project-e4ac1',
    databaseURL: 'https://api-project-e4ac1-default-rtdb.firebaseio.com',
    storageBucket: 'api-project-e4ac1.firebasestorage.app',
    iosBundleId: 'com.example.iteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8A49KCO4OwwTggOVfj5uhl0d5bV9_Gk',
    appId: '1:507753071893:web:d042dd66ebcc56b16b951c',
    messagingSenderId: '507753071893',
    projectId: 'api-project-e4ac1',
    authDomain: 'api-project-e4ac1.firebaseapp.com',
    databaseURL: 'https://api-project-e4ac1-default-rtdb.firebaseio.com',
    storageBucket: 'api-project-e4ac1.firebasestorage.app',
  );
}
